module.exports = {
    extends: ['stylelint-config-standard', 'css-properties-sorting'],
    plugins: ['stylelint-order'], // stylelint-order是CSS属性排序插件
    rules: {
      'no-descending-specificity': null,
      'length-zero-no-unit': true, // 禁止单位为0的单位后面添加单位
      'number-leading-zero': 'never', // 要求或不允许小数小于1（可自动修复）的前导零
      'number-no-trailing-zeros': true,
      'string-quotes': 'single',
      'color-no-invalid-hex': true,
      'comment-no-empty': true,
      'rule-empty-line-before': 'never',
      // 现在代码中的类名中有包含大写定义的命名，正则中添加包含大写字母
      'selector-class-pattern': '^[a-zA-Z]+([a-zA-Z0-9]?|[a-zA-Z0-9\\-\\_\\--]*[a-zA-Z0-9])$', // 指定一个模式类选择符，限制选择器名称写法
      'selector-id-pattern': '^[a-zA-Z]+([a-zA-Z0-9]?|[a-zA-Z0-9\\-\\_\\--]*[a-zA-Z0-9])$',
      // 'value-keyword-case': 'lower', // 属性值小写
      'no-empty-source': true, // 不允许空的来源
      'at-rule-no-unknown': null, // 不允许at-rules不明， 代码中的scss中有使用到@include、@mixin等，会报错
      'indentation': 2, // 指定缩进(stylelint-config-standard)
      // 'max-nesting-depth': 3, // 允许嵌套的深度为3
      'no-duplicate-selectors': true, // 不允许重复的选择器
      'no-eol-whitespace': true, // 不允许行尾空白(stylelint-config-standard)
      // "no-invalid-double-slash-comments": true // 不允许双斜杠注释(/ /…)不支持CSS(stylelint-config-standard)
  
      'order/order': [ // 指定声明块内的内容顺序
        ['custom-properties', 'declarations'], {
          disableFix: true
        }
      ],
      'order/properties-order': [ // 指定声明块内属性的字母顺序
        'position',
        'top',
        'right',
        'bottom',
        'left',
        // 'z-index',
        // 'display',
        // 'float',
        // 'width',
        // 'height',
        // 'max-width',
        // 'max-height',
        // 'min-width',
        // 'min-height',
        // 'padding',
        // 'padding-top',
        // 'padding-right',
        // 'padding-bottom',
        // 'padding-left',
        // 'margin',
        // 'margin-top',
        // 'margin-right',
        // 'margin-bottom',
        // 'margin-left',
        // 'margin-collapse',
        // 'margin-top-collapse',
        // 'margin-right-collapse',
        // 'margin-bottom-collapse',
        // 'margin-left-collapse',
        // 'overflow',
        // 'overflow-x',
        // 'overflow-y',
        // 'clip',
        // 'clear',
        // 'font',
        // 'font-family',
        // 'font-size',
        // 'font-smoothing',
        // 'osx-font-smoothing',
        // 'font-style',
        // 'font-weight',
        // 'hyphens',
        // 'src',
        // 'line-height',
        // 'letter-spacing',
        // 'word-spacing',
        // 'color',
        // 'text-align',
        // 'text-decoration',
        // 'text-indent',
        // 'text-overflow',
        // 'text-rendering',
        // 'text-size-adjust',
        // 'text-shadow',
        // 'text-transform',
        // 'word-break',
        // 'word-wrap',
        // 'white-space',
        // 'vertical-align',
        // 'list-style',
        // 'list-style-type',
        // 'list-style-position',
        // 'list-style-image',
        // 'pointer-events',
        // 'cursor',
        // 'background',
        // 'background-attachment',
        // 'background-color',
        // 'background-image',
        // 'background-position',
        // 'background-repeat',
        // 'background-size',
        // 'border',
        // 'border-collapse',
        // 'border-top',
        // 'border-right',
        // 'border-bottom',
        // 'border-left',
        // 'border-color',
        // 'border-image',
        // 'border-top-color',
        // 'border-right-color',
        // 'border-bottom-color',
        // 'border-left-color',
        // 'border-spacing',
        // 'border-style',
        // 'border-top-style',
        // 'border-right-style',
        // 'border-bottom-style',
        // 'border-left-style',
        // 'border-width',
        // 'border-top-width',
        // 'border-right-width',
        // 'border-bottom-width',
        // 'border-left-width',
        // 'border-radius',
        // 'border-top-right-radius',
        // 'border-bottom-right-radius',
        // 'border-bottom-left-radius',
        // 'border-top-left-radius',
        // 'border-radius-topright',
        // 'border-radius-bottomright',
        // 'border-radius-bottomleft',
        // 'border-radius-topleft',
        // 'content',
        // 'quotes',
        // 'outline',
        // 'outline-offset',
        // 'opacity',
        // 'filter',
        // 'visibility',
        // 'size',
        // 'zoom',
        // 'transform',
        // 'box-align',
        // 'box-flex',
        // 'box-orient',
        // 'box-pack',
        // 'box-shadow',
        // 'box-sizing',
        // 'table-layout',
        // 'animation',
        // 'animation-delay',
        // 'animation-duration',
        // 'animation-iteration-count',
        // 'animation-name',
        // 'animation-play-state',
        // 'animation-timing-function',
        // 'animation-fill-mode',
        // 'transition',
        // 'transition-delay',
        // 'transition-duration',
        // 'transition-property',
        // 'transition-timing-function',
        // 'background-clip',
        // 'backface-visibility',
        // 'resize',
        // 'appearance',
        // 'user-select',
        // 'interpolation-mode',
        // 'direction',
        // 'marks',
        // 'page',
        // 'set-link-source',
        // 'unicode-bidi',
        // 'speak'
      ]
    }
  }
  